import { z } from "zod";

const recordSchema = z.record(z.unknown());
const positionSchema = z.object({ x: z.number(), y: z.number() });
const viewportSchema = z.object({ x: z.number(), y: z.number(), k: z.number() });
const nodeTypeSchema = z.enum(["image", "text", "config", "video", "audio"]);
const generationModeSchema = z.enum(["text", "image", "video", "audio"]);

/** Canvas Agent 对外提供的工具名称。 */
export const toolNames = [
    "site_navigate",
    "canvas_list_projects",
    "canvas_get_state",
    "canvas_get_selection",
    "canvas_export_snapshot",
    "canvas_apply_ops",
    "canvas_create_node",
    "canvas_create_attachment_nodes",
    "canvas_create_text_node",
    "canvas_create_text_nodes",
    "canvas_create_config_node",
    "canvas_create_image_prompt_flow",
    "canvas_create_generation_flow",
    "canvas_generate_text",
    "canvas_generate_image",
    "canvas_generate_video",
    "canvas_generate_audio",
    "canvas_update_node",
    "canvas_update_node_text",
    "canvas_move_nodes",
    "canvas_resize_node",
    "canvas_delete_nodes",
    "canvas_connect_nodes",
    "canvas_select_nodes",
    "canvas_set_viewport",
    "canvas_run_generation",
    "generation_get_status",
    "workbench_image_get_config",
    "workbench_image_generate",
    "workbench_video_get_config",
    "workbench_video_generate",
    "prompts_search",
    "assets_list",
    "assets_add",
    "project_context",
    "project_gates",
    "project_list_jobs",
    "project_list_runs",
    "project_run_status",
    "project_run_qc",
    "project_stage_items",
    "project_run_stage",
    "project_cancel_stage",
    "project_retry_failed",
    "project_update_stage_input",
    "project_regenerate_item",
    "project_patch_shot",
    "project_confirm_casting",
    "project_assemble",
    "project_adopt_candidate",
    "project_asset_pack",
    "project_attach_asset",
    "project_export_package",
] as const;
export type ToolName = (typeof toolNames)[number];

export const canvasOpSchema = z.discriminatedUnion("type", [
    z.object({ type: z.literal("add_node"), nodeType: nodeTypeSchema.optional(), id: z.string().optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), position: positionSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("update_node"), id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("delete_node"), id: z.string().optional(), ids: z.array(z.string()).optional() }).passthrough(),
    z.object({ type: z.literal("delete_connections"), id: z.string().optional(), ids: z.array(z.string()).optional(), all: z.boolean().optional() }).passthrough(),
    z.object({ type: z.literal("connect_nodes"), id: z.string().optional(), fromNodeId: z.string(), toNodeId: z.string() }).passthrough(),
    z.object({ type: z.literal("set_viewport"), viewport: viewportSchema }).passthrough(),
    z.object({ type: z.literal("select_nodes"), ids: z.array(z.string()) }).passthrough(),
    z.object({ type: z.literal("run_generation"), nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }).passthrough(),
]);

const textNodeSchema = z.object({
    text: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    width: z.number().optional(),
    height: z.number().optional(),
});

const generationOptionsSchema = z.object({
    model: z.string().optional(),
    size: z.string().optional(),
    quality: z.string().optional(),
    count: z.number().optional(),
    seconds: z.string().optional(),
    vquality: z.string().optional(),
    generateAudio: z.string().optional(),
    watermark: z.string().optional(),
    videoMode: z.string().optional(),
    audioVoice: z.string().optional(),
    audioFormat: z.string().optional(),
    audioSpeed: z.string().optional(),
    audioInstructions: z.string().optional(),
});

const generationFlowSchema = z.object({
    prompt: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    referenceNodeIds: z.array(z.string()).optional(),
});

export const toolInputSchemas = {
    site_navigate: z.object({ path: z.string() }),
    canvas_list_projects: z.object({ keyword: z.string().optional(), page: z.number().optional(), pageSize: z.number().optional() }),
    canvas_get_state: z.object({}).passthrough(),
    canvas_get_selection: z.object({}).passthrough(),
    canvas_export_snapshot: z.object({}).passthrough(),
    canvas_apply_ops: z.object({ ops: z.array(canvasOpSchema) }),
    canvas_create_node: z.object({ nodeType: nodeTypeSchema, title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), metadata: recordSchema.optional() }),
    canvas_create_attachment_nodes: z.object({ attachmentIds: z.array(z.string()).min(1), x: z.number().optional(), y: z.number().optional(), gap: z.number().optional(), direction: z.enum(["row", "column"]).optional() }),
    canvas_create_text_node: z.object({ text: z.string().optional(), x: z.number().optional(), y: z.number().optional(), title: z.string().optional(), width: z.number().optional(), height: z.number().optional() }),
    canvas_create_text_nodes: z.object({ items: z.array(textNodeSchema).min(1), x: z.number().optional(), y: z.number().optional(), gap: z.number().optional(), direction: z.enum(["row", "column"]).optional() }),
    canvas_create_config_node: z.object({ prompt: z.string().optional(), mode: generationModeSchema.optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_image_prompt_flow: z.object({ prompt: z.string(), x: z.number().optional(), y: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_generation_flow: generationFlowSchema.extend({ mode: generationModeSchema.optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_generate_text: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_image: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_video: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_audio: generationFlowSchema.merge(generationOptionsSchema),
    canvas_update_node: z.object({ id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }),
    canvas_update_node_text: z.object({ id: z.string(), text: z.string(), title: z.string().optional() }),
    canvas_move_nodes: z.object({ items: z.array(z.object({ id: z.string(), x: z.number().optional(), y: z.number().optional(), dx: z.number().optional(), dy: z.number().optional() })).min(1) }),
    canvas_resize_node: z.object({ id: z.string(), width: z.number(), height: z.number(), freeResize: z.boolean().optional() }),
    canvas_delete_nodes: z.object({ ids: z.array(z.string()).min(1) }),
    canvas_connect_nodes: z.object({ connections: z.array(z.object({ fromNodeId: z.string(), toNodeId: z.string() })).min(1) }),
    canvas_select_nodes: z.object({ ids: z.array(z.string()) }),
    canvas_set_viewport: z.object({ viewport: viewportSchema }),
    canvas_run_generation: z.object({ nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }),
    generation_get_status: z.object({ scope: z.enum(["all", "canvas", "image", "video"]).optional(), taskId: z.string().optional(), nodeIds: z.array(z.string()).optional(), limit: z.number().optional() }),
    workbench_image_get_config: z.object({}).passthrough(),
    workbench_image_generate: z.object({ prompt: z.string(), model: z.string().optional(), quality: z.string().optional(), size: z.string().optional(), count: z.number().optional(), run: z.boolean().optional() }),
    workbench_video_get_config: z.object({}).passthrough(),
    workbench_video_generate: z.object({ prompt: z.string(), model: z.string().optional(), size: z.string().optional(), seconds: z.string().optional(), resolution: z.string().optional(), generateAudio: z.boolean().optional(), watermark: z.boolean().optional(), mode: z.enum(["frames", "reference"]).optional(), run: z.boolean().optional() }),
    prompts_search: z.object({ keyword: z.string().optional(), category: z.string().optional(), tags: z.array(z.string()).optional(), page: z.number().optional(), pageSize: z.number().optional() }),
    assets_list: z.object({ kind: z.enum(["all", "text", "image", "video"]).optional(), keyword: z.string().optional(), page: z.number().optional(), pageSize: z.number().optional() }),
    assets_add: z.object({ kind: z.enum(["text", "image"]), title: z.string(), content: z.string().optional(), imageUrl: z.string().optional(), tags: z.array(z.string()).optional(), source: z.string().optional(), note: z.string().optional() }),
    // ——— project_*：Agent 驱动服务端项目/流水线（M5）。
    // 与 canvas_* 的关键区别：**走网关 HTTP，不依赖网页画布连接**，
    // 因此 Agent 能在没有前端页面打开时也能读项目、跑阶段、看任务、取交付包。
    project_context: z.object({ projectId: z.string() }),
    project_gates: z.object({ projectId: z.string() }),
    project_list_jobs: z.object({ status: z.enum(["queued", "running", "done", "error", "canceled"]).optional(), kind: z.string().optional(), limit: z.number().optional() }),
    project_list_runs: z.object({ projectId: z.string().optional(), limit: z.number().optional() }),
    project_run_status: z.object({ runId: z.string() }),
    project_run_qc: z.object({ runId: z.string() }),
    project_stage_items: z.object({ runId: z.string(), stage: z.string() }),
    project_run_stage: z.object({ runId: z.string(), stage: z.string(), options: recordSchema.optional() }),
    project_cancel_stage: z.object({ runId: z.string(), stage: z.string() }),
    project_retry_failed: z.object({ runId: z.string(), stage: z.string() }),
    project_update_stage_input: z.object({ runId: z.string(), stage: z.string(), patch: recordSchema }),
    project_regenerate_item: z.object({ runId: z.string(), stage: z.string(), itemId: z.string(), template: z.string().optional(), params: recordSchema.optional(), promptOverride: z.string().optional() }),
    project_patch_shot: z.object({ runId: z.string(), shotId: z.string(), patch: recordSchema, stage: z.string().optional() }),
    project_confirm_casting: z.object({ runId: z.string(), characterId: z.string(), face: z.boolean().optional(), voice: z.boolean().optional(), speaker: z.string().optional(), design: z.string().optional(), language: z.string().optional(), speed: z.number().optional(), previewArtifactId: z.string().optional(), closeupArtifactId: z.string().optional() }),
    project_assemble: z.object({ runId: z.string(), options: recordSchema.optional() }),
    /** 采用某个候选：jobId 传 null 表示撤销采用（与 M3 的 select 语义一致）。 */
    project_adopt_candidate: z.object({ projectId: z.string(), shotId: z.string(), slotId: z.string(), jobId: z.string().nullable() }),
    project_asset_pack: z.object({ projectId: z.string().optional(), role: z.string().optional(), runId: z.string().optional() }),
    project_attach_asset: z.object({
        projectId: z.string(),
        role: z.string(),
        bindingId: z.string(),
        artifactId: z.string(),
        artifactIds: z.array(z.string()).optional(),
        selectedArtifactId: z.string().nullable().optional(),
        select: z.boolean().optional(),
        sourceJobId: z.string().optional(),
        stageId: z.string().optional(),
        name: z.string().optional(),
        episodeId: z.string().optional(),
        sceneId: z.string().optional(),
        shotId: z.string().optional(),
    }),
    project_export_package: z.object({ runId: z.string(), episodeId: z.string().optional(), allowPartial: z.boolean().optional(), steps: z.array(z.string()).optional() }),
} satisfies Record<ToolName, z.AnyZodObject>;

export const toolDescriptions: Record<ToolName, string> = {
    site_navigate: "跳转网站页面。path 可为 / (首页)、/canvas (我的画布)、/canvas/:id (指定画布)、/image (生图工作台)、/video (视频创作台)、/prompts (提示词库)、/assets (我的素材)、/config (配置)。操作画布前若不在画布页，先用本工具打开画布。",
    canvas_list_projects: "列出用户全部画布（仅标题、创建/更新时间、节点数、连线数，不含完整数据），支持 keyword 搜索和 page/pageSize 分页。返回的 id 可配合 site_navigate 跳转到 /canvas/:id 打开对应画布。",
    canvas_get_state: "读取当前网页画布的节点、连线、选区和视口。",
    canvas_get_selection: "读取当前网页画布选中的节点。",
    canvas_export_snapshot: "导出当前画布快照，用于理解布局。",
    canvas_apply_ops: "批量操作当前网页画布。ops 支持 add_node、update_node、delete_node、delete_connections、connect_nodes、set_viewport、select_nodes、run_generation。",
    canvas_create_node: "创建任意类型节点：text、image、config、video、audio。适合创建占位图、媒体占位、配置节点或自定义 metadata 节点。",
    canvas_create_attachment_nodes: "把当前对话中用户上传的图片附件创建成真实画布图片节点。attachmentIds 使用本轮附件清单中的 ID；返回的节点 ID 可传给 canvas_create_generation_flow.referenceNodeIds 作为生成参考图。",
    canvas_create_text_node: "在当前画布创建单个文本节点。",
    canvas_create_text_nodes: "批量创建文本节点，适合生成标题、段落、脚本、说明等内容块。",
    canvas_create_config_node: "创建生成配置节点，可指定 text/image/video/audio 模式和生成参数，可选择立即触发生成。",
    canvas_create_image_prompt_flow: "创建提示词文本节点和图片生成配置节点，并自动连线，可选择立即触发生图。",
    canvas_create_generation_flow: "创建通用生成流程：提示词文本节点、生成配置节点、参考节点连线，可用于文案、生图、视频或音频。",
    canvas_generate_text: "创建通用文本生成流程并立即触发生成。",
    canvas_generate_image: "创建通用图片生成流程并立即触发生成。",
    canvas_generate_video: "创建通用视频生成流程并立即触发生成。",
    canvas_generate_audio: "创建通用音频生成流程并立即触发生成。",
    canvas_update_node: "更新节点基础字段或 metadata。",
    canvas_update_node_text: "更新文本节点内容和标题。",
    canvas_move_nodes: "移动一个或多个节点，支持绝对坐标或 dx/dy 偏移。",
    canvas_resize_node: "调整节点尺寸。",
    canvas_delete_nodes: "删除指定节点及相关连线。",
    canvas_connect_nodes: "批量连接节点。",
    canvas_select_nodes: "设置当前选中节点。",
    canvas_set_viewport: "调整画布视口。",
    canvas_run_generation: "触发指定节点生成，通常用于配置节点或文本/图片/视频/音频节点。",
    generation_get_status: "查询当前活动网页的生成任务状态。默认返回画布、生图工作台和视频工作台最近任务；可用 scope 过滤来源，用 taskId 查询工作台任务，用 nodeIds 查询画布节点。",
    workbench_image_get_config: "读取生图工作台的当前参数和可选项（可用模型、质量、分辨率 1k/2k/4k/auto、宽高比、张数范围），在调用 workbench_image_generate 前先了解可选值。",
    workbench_image_generate: "在生图工作台填入提示词并按需设置 model、quality、size（如 16:9 或 2048x1152）、count，run 默认 true 会自动点击生成按钮。会自动跳转到生图工作台。生成为异步过程，提交后返回 taskId，可用 generation_get_status 查询状态。",
    workbench_video_get_config: "读取视频创作台的当前参数和可选项（可用模型、清晰度 480/720/1080、比例 1:1/3:4/4:3/16:9/9:16/21:9/auto、时长 4–30 秒、首尾帧或全能参考模式、是否生成声音与水印）。",
    workbench_video_generate: "在视频创作台填入提示词并按需设置 model、size（1:1、3:4、4:3、16:9、9:16、21:9、auto 或 1280x720）、seconds（4–30）、resolution（480/720/1080）、generateAudio、watermark、mode（frames 首尾帧 / reference 全能参考），run 默认 true 会自动点击生成按钮。会自动跳转到视频创作台。生成为异步过程，提交后返回 taskId，可用 generation_get_status 查询状态。",
    prompts_search: "搜索提示词库（第三方提示词合集），支持 keyword、category、tags 过滤和 page/pageSize 分页，返回标题、提示词、分类、标签、封面等。",
    assets_list: "列出用户「我的素材」，支持 kind（text/image/video）过滤、keyword 搜索和 page/pageSize 分页。为控制体积不返回图片/视频原始 data，仅返回封面与元信息。",
    assets_add: "向「我的素材」新增素材。kind=text 时用 content 传文本内容；kind=image 时用 imageUrl 传图片地址或 dataURL。可附带 title、tags、source、note。",
    project_context: "读取服务端项目的上下文：基本信息、风格锚点、plan、七段式集/场/镜进度、关联的 runIds 与画布 id、资产引用数。**这是 Agent 了解「服务端短剧项目」的唯一入口，与 canvas_get_state（读网页画布）完全不同**：不需要前端页面已打开。批量生产的第一步。",
    project_gates: "读取项目的阶段门禁：七段（script/storyboard/design/casting/keyframe/audio/assembly）各自 status 与 blockedBy（被哪个上游挡住）。跑某个阶段前先用它确认能不能跑，避免白等。",
    project_list_jobs: "列出服务端生成任务（生图/生视频/配音等），可按 status 与 kind 过滤。用于「批量入队后等终态」「只重试失败的那些」——重复调用不会重复入队（服务端按幂等键去重）。",
    project_list_runs: "列出服务端全部流水线 run（裁剪版：只回 id/标题/所属项目/时间/各阶段状态，**不含剧本文本**）。可按 projectId 过滤。Agent 的「上帝视角」入口：先看有哪些 run、各自跑到哪一段，再决定操作谁。",
    project_run_status: "读某个 run 的轻量进度（progress.json：当前阶段、done/total、ETA、是否 inflight）。**轮询只用它**——不要频繁调 project_stage_items，那个会拉整个 run。",
    project_run_qc: "读某个 run 的质检报告（各接缝/响度/一致性指标与 needsReview 标记）。注意：**没报警不等于没问题**，指标接近门槛时主动提示用户人工复核。",
    project_stage_items: "读某个 run 指定阶段的**条目清单**（裁剪版）：分镜→镜头(id/景别/动作/对白/时长)、定妆→角色(脸/声确认态)、关键帧→帧(id/状态/候选数/选中)、配音→台词(id/文本/语速/状态)、成片→片段与合成状态。**精调前必须先调它拿到 itemId/shotId/characterId**，再配 project_patch_shot / project_regenerate_item / project_confirm_casting 使用。",
    project_run_stage: "触发服务端流水线某个阶段：runId + stage（如 storyboard/keyframe/assembly）。**202 立刻返回**，真实生成在后台跑；用 project_run_status 看进度。阶段未就绪会被门禁拒绝并给出可读原因。",
    project_cancel_stage: "取消服务端流水线正在执行的某个阶段（runId + stage）。已完成的阶段不受影响。",
    project_retry_failed: "重试某阶段内**失败的条目**（202，后台补跑，成功的不重跑）。阶段跑完但有部分条目 error 时用它，比整阶段重跑省算力。",
    project_update_stage_input: "改某阶段的输入参数（如模型、时长、风格强度），patch 为键值对。**改完要再调 project_run_stage 才生效**。用于「换模型重跑这一段」。",
    project_regenerate_item: "给单个条目**追加一个候选**（换模板/参数/提示词再出一份）：itemId 来自 project_stage_items。promptOverride 是人工改词——只覆盖提示词，尺寸/参考图/采样参数仍走规则表，不破坏身份锁定。202 立刻返回，新候选自动选中。",
    project_patch_shot: "改 run 内某个镜头的字段（景别/机位/动作/对白/时长等，patch 为键值对）。stage 默认 storyboard。shotId 来自 project_stage_items。改完对白后通常要配 project_regenerate_item 重录对应配音。",
    project_confirm_casting: "角色定妆确认（锁脸/锁声音的人工动作）：characterId + face/voice 确认位，可带 speaker/design/language/speed。**换脸**：先 project_asset_pack({runId}) 看 candidates，再传 closeupArtifactId + face:true，来源会被记为 pack（人工选用）并在重跑时保留。确认后自动解除 keyframe/audio 的 casting 阻断。批量生产前必须全部确认。",
    project_assemble: "触发「片段 → 成片」合成（assembly 阶段的执行体）：按 assembly.order 拼接、逐段响度归一、接缝淡化。202 立刻返回，ffmpeg 是分钟级，用 project_run_status 等终态。合成完用 project_export_package 取交付包。",
    project_adopt_candidate: "采用/撤销采用某个槽位候选。传 jobId 采用（写入 slot.selected），传 **null 撤销采用**（幂等、不动候选数组）。这是「批量生成后由 Agent 逐个确认采用」的关键动作。",
    project_asset_pack: "读取项目资料包现状。两种用法：给 projectId → 每个角色的/场景/道具绑了哪些参考图、几个候选、有没有选定（status: adopted/candidates/missing），missing 的实体就是必须先补的缺口；给 runId → **定妆取料盘点**（castingFaces：每张脸当前用哪张、source=pack/design/prev/none、还有哪些 candidates 可换）。想推进定妆或换脸前先调它。",
    project_attach_asset: "把一个产物归入项目资料包，挂到某个实体上（role + bindingId），之后它就是该实体的参考图。artifactId 必须是网关产物地址 /api/artifacts/<jobId>/<file>。**幂等**：同 role+bindingId 重复调用只会追加候选，不会造出重复引用。",
    project_export_package: "导出完整交付包：自动粗剪成片 + clips/ 分集原片 + SRT + FCPXML + EDL + 清单 + 说明，打成 zip。**202 立刻返回**（真实 ffmpeg 是分钟级），完成后用 GET 同路径读 manifest。与浏览器端的「成片+字幕」下载不同，这个含剪辑工程文件，可直接导入剪映继续剪。",
};
